
table Torappu_Battle_BakedFrameData {
	position:[float];
	rotation:[float];
	scale:[float];
}



table Torappu_Battle_BakedMountPointData {
	isConstant:bool;
	bakedStepInterval:int32;
	frames:[Torappu_Battle_BakedFrameData];
}



table Dict_2_System_Int32_Torappu_Battle_BakedMountPointData_ {
	dict_key:int32;
	dict_value:Torappu_Battle_BakedMountPointData;
}



table Dict_2_System_String_Dict_2_System_Int32_Torappu_Battle_BakedMountPointData__ {
	dict_key:string;
	dict_value:[Dict_2_System_Int32_Torappu_Battle_BakedMountPointData_];
}



table Torappu_Battle_BakedEventTimeline {
	eventTime:[float];
	events:[string];
}



table Dict_2_System_String_Torappu_Battle_BakedEventTimeline_ {
	dict_key:string;
	dict_value:Torappu_Battle_BakedEventTimeline;
}



table Torappu_Battle_BakedAnimData {
	md5:string;
	skipZeroFrameUpdate:bool;
	bakedMPDatas:[Dict_2_System_String_Dict_2_System_Int32_Torappu_Battle_BakedMountPointData__];
	bakedEvents:[Dict_2_System_String_Torappu_Battle_BakedEventTimeline_];
}



table Dict_2_System_String_Torappu_Battle_BakedAnimData_ {
	dict_key:string;
	dict_value:Torappu_Battle_BakedAnimData;
}



table Torappu_Battle_BakedSpineData {
	bakedAnimDatas:[Dict_2_System_String_Torappu_Battle_BakedAnimData_];
}



root_type Torappu_Battle_BakedSpineData;