
enum Torappu_PlayerAvatarGroupType : int32 {
	NONE = 0,
	ASSISTANT = 1,
	DEFAULT = 2,
	SPECIAL = 3,
	ACTIVITY = 4,
	DYNAMIC = 5
}

table Torappu_PlayerAvatarLimitData {
	avatarId:string;
	descShowTs:int64;
	descHideTs:int64;
}



table Torappu_PlayerAvatarPerData {
	avatarId:string;
	avatarType:Torappu_PlayerAvatarGroupType;
	avatarDesc:string;
	isSecret:bool;
	avatarStartTs:int64;
	avatarLimit:bool;
	avatarIdSort:int32;
	avatarIdDesc:string;
	avatarItemName:string;
	avatarItemDesc:string;
	avatarItemUsage:string;
	obtainApproach:string;
	dynAvatarId:string;
	limitDatas:[Torappu_PlayerAvatarLimitData];
}



table Torappu_PlayerAvatarGroupData {
	avatarType:Torappu_PlayerAvatarGroupType;
	typeName:string;
	sortId:int32;
	avatarIdList:[string];
}



table Dict_2_Torappu_PlayerAvatarGroupType_Torappu_PlayerAvatarGroupData_ {
	dict_key:Torappu_PlayerAvatarGroupType;
	dict_value:Torappu_PlayerAvatarGroupData;
}



table Torappu_AvatarConstData {
	approachHideText:string;
}



table Torappu_PlayerAvatarData {
	defaultAvatarId:string;
	avatarList:[Torappu_PlayerAvatarPerData];
	avatarTypeData:[Dict_2_Torappu_PlayerAvatarGroupType_Torappu_PlayerAvatarGroupData_];
	constData:Torappu_AvatarConstData;
}



enum Torappu_HomeMultiFormChangeRule : int32 {
	NONE = 0,
	TIME = 1
}

table Torappu_HomeBackgroundMultiFormData {
	multiFormBgId:string;
	sortId:int32;
	bgMusicId:string;
}



table Torappu_HomeBackgroundSingleData {
	bgId:string;
	bgType:string;
	bgSortId:int32;
	bgStartTime:int64;
	isSecret:bool;
	bgName:string;
	bgDes:string;
	bgUsage:string;
	isMultiForm:bool;
	changeRule:Torappu_HomeMultiFormChangeRule;
	multiFormList:[Torappu_HomeBackgroundMultiFormData];
	obtainApproach:string;
	unlockDesList:[string];
	multiPicId:string;
}



table Torappu_ArtGalleryItemData {
	id:string;
	groupType:string;
	sortId:int32;
}



table Torappu_ArtGalleryGroupData {
	type:string;
	title:string;
	sortId:int32;
	items:[Torappu_ArtGalleryItemData];
}



table Torappu_HomeThemeMultiFormData {
	multiFormTmId:string;
	sortId:int32;
}



enum Torappu_ItemRarity : int32 {
	TIER_1 = 0,
	TIER_2 = 1,
	TIER_3 = 2,
	TIER_4 = 3,
	TIER_5 = 4,
	TIER_6 = 5,
	E_NUM = 6
}

table Torappu_HomeThemeDisplayData {
	id:string;
	type:string;
	sortId:int32;
	startTime:int64;
	isSecret:bool;
	tmName:string;
	tmDes:string;
	tmUsage:string;
	isMultiForm:bool;
	changeRule:Torappu_HomeMultiFormChangeRule;
	multiFormList:[Torappu_HomeThemeMultiFormData];
	obtainApproach:string;
	unlockDesList:[string];
	isLimitObtain:bool;
	hideWhenLimit:bool;
	rarity:Torappu_ItemRarity;
	multiPicId:string;
}



table Torappu_HomeBackgroundLimitInfoData {
	limitInfoId:string;
	startTime:int64;
	endTime:int64;
	invalidObtainDesc:string;
	displayAfterEndTime:bool;
}



table Torappu_HomeBackgroundLimitData {
	bgId:string;
	limitInfos:[Torappu_HomeBackgroundLimitInfoData];
}



table Dict_2_System_String_Torappu_HomeBackgroundLimitData_ {
	dict_key:string;
	dict_value:Torappu_HomeBackgroundLimitData;
}



table Torappu_HomeThemeLimitInfoData {
	startTime:int64;
	endTime:int64;
	invalidObtainDesc:string;
}



table Torappu_HomeThemeLimitData {
	id:string;
	limitInfos:[Torappu_HomeThemeLimitInfoData];
}



table Dict_2_System_String_Torappu_HomeThemeLimitData_ {
	dict_key:string;
	dict_value:Torappu_HomeThemeLimitData;
}



table Torappu_HomeMultiFormInfoData {
	changeRule:Torappu_HomeMultiFormChangeRule;
	bgDesc:string;
	tmDesc:string;
}



table Torappu_HomeMultiFormTimeRuleData {
	id:string;
	startHour:int32;
}



table Dict_2_System_String_List_1_Torappu_HomeMultiFormTimeRuleData__ {
	dict_key:string;
	dict_value:[Torappu_HomeMultiFormTimeRuleData];
}



table Torappu_HomeBackgroundData {
	defaultBackgroundId:string;
	defaultThemeId:string;
	homeBgDataList:[Torappu_HomeBackgroundSingleData];
	backgroundGroupDatas:[Torappu_ArtGalleryGroupData];
	themeList:[Torappu_HomeThemeDisplayData];
	themeGroupDatas:[Torappu_ArtGalleryGroupData];
	backgroundLimitData:[Dict_2_System_String_Torappu_HomeBackgroundLimitData_];
	themeLimitData:[Dict_2_System_String_Torappu_HomeThemeLimitData_];
	multiFormInfoData:[Torappu_HomeMultiFormInfoData];
	timeRuleData:[Dict_2_System_String_List_1_Torappu_HomeMultiFormTimeRuleData__];
	defaultBgMusicId:string;
	themeStartTime:int64;
}



enum Torappu_NameCardV2ModuleType : int32 {
	NONE = 0,
	BACKGROUND = 1,
	ILLUST = 2,
	COLLECT = 3,
	AVATAR = 4,
	REMOVABLE = 5,
	AVATAR_SIMPLE = 6
}

table Torappu_NameCardV2ModuleData {
	id:string;
	type:Torappu_NameCardV2ModuleType;
}



table Dict_2_System_String_Torappu_NameCardV2ModuleData_ {
	dict_key:string;
	dict_value:Torappu_NameCardV2ModuleData;
}



enum Torappu_NameCardV2ModuleSubType : int32 {
	NONE = 0,
	SIGN = 1,
	ASSIST = 2,
	MEDAL = 3,
	MAINLINE = 4,
	EQUIPMENT = 5
}

table Torappu_NameCardV2RemovableModuleData {
	sortId:int32;
	subType:Torappu_NameCardV2ModuleSubType;
	name:string;
	id:string;
	type:Torappu_NameCardV2ModuleType;
}



table Dict_2_System_String_Torappu_NameCardV2RemovableModuleData_ {
	dict_key:string;
	dict_value:Torappu_NameCardV2RemovableModuleData;
}



enum Torappu_NameCardV2SkinType : int32 {
	NONE = 0,
	BASE = 1,
	SPECIAL = 2
}

table Torappu_NameCardV2TimeLimitInfo {
	limitId:string;
	id:string;
	availStartTime:int64;
	availEndTime:int64;
}



table Dict_2_System_String_Torappu_NameCardV2TimeLimitInfo_ {
	dict_key:string;
	dict_value:Torappu_NameCardV2TimeLimitInfo;
}



table Torappu_NameCardV2SkinData {
	id:string;
	name:string;
	type:Torappu_NameCardV2SkinType;
	isSecret:bool;
	sortId:int32;
	isSpTheme:bool;
	defaultShowDetail:bool;
	themeName:string;
	themeEnName:string;
	skinStartTime:int64;
	skinDesc:string;
	usageDesc:string;
	skinApproach:string;
	unlockConditionCnt:int32;
	unlockDescList:[string];
	fixedModuleList:[string];
	rarity:Torappu_ItemRarity;
	skinTmplCnt:int32;
	canChangeTmpl:bool;
	isTimeLimit:bool;
	timeLimitInfoList:[Dict_2_System_String_Torappu_NameCardV2TimeLimitInfo_];
}



table Dict_2_System_String_Torappu_NameCardV2SkinData_ {
	dict_key:string;
	dict_value:Torappu_NameCardV2SkinData;
}



table Torappu_NameCardV2Consts {
	defaultNameCardSkinId:string;
	canUidHide:bool;
	removableModuleMaxCount:int32;
	approachHideText:string;
}



table Torappu_NameCardV2Data {
	fixedModuleData:[Dict_2_System_String_Torappu_NameCardV2ModuleData_];
	removableModuleData:[Dict_2_System_String_Torappu_NameCardV2RemovableModuleData_];
	skinData:[Dict_2_System_String_Torappu_NameCardV2SkinData_];
	skinGroupDatas:[Torappu_ArtGalleryGroupData];
	consts:Torappu_NameCardV2Consts;
}



enum Torappu_MailArchiveItemType : int32 {
	NORMAL = 0,
	BIRTHDAY = 1,
	OPEN_SERVER = 2
}

enum Torappu_ItemType : int32 {
	NONE = 0,
	CHAR = 1,
	CARD_EXP = 2,
	MATERIAL = 3,
	GOLD = 4,
	EXP_PLAYER = 5,
	TKT_TRY = 6,
	TKT_RECRUIT = 7,
	TKT_INST_FIN = 8,
	TKT_GACHA = 9,
	ACTIVITY_COIN = 10,
	DIAMOND = 11,
	DIAMOND_SHD = 12,
	HGG_SHD = 13,
	LGG_SHD = 14,
	FURN = 15,
	AP_GAMEPLAY = 16,
	AP_BASE = 17,
	SOCIAL_PT = 18,
	CHAR_SKIN = 19,
	TKT_GACHA_10 = 20,
	TKT_GACHA_PRSV = 21,
	AP_ITEM = 22,
	AP_SUPPLY = 23,
	RENAMING_CARD = 24,
	RENAMING_CARD_2 = 25,
	ET_STAGE = 26,
	ACTIVITY_ITEM = 27,
	VOUCHER_PICK = 28,
	VOUCHER_CGACHA = 29,
	VOUCHER_MGACHA = 30,
	CRS_SHOP_COIN = 31,
	CRS_RUNE_COIN = 32,
	LMTGS_COIN = 33,
	EPGS_COIN = 34,
	LIMITED_TKT_GACHA_10 = 35,
	LIMITED_FREE_GACHA = 36,
	REP_COIN = 37,
	ROGUELIKE = 38,
	LINKAGE_TKT_GACHA_10 = 39,
	VOUCHER_ELITE_II_4 = 40,
	VOUCHER_ELITE_II_5 = 41,
	VOUCHER_ELITE_II_6 = 42,
	VOUCHER_SKIN = 43,
	RETRO_COIN = 44,
	PLAYER_AVATAR = 45,
	UNI_COLLECTION = 46,
	VOUCHER_FULL_POTENTIAL = 47,
	RL_COIN = 48,
	RETURN_CREDIT = 49,
	MEDAL = 50,
	CHARM = 51,
	HOME_BACKGROUND = 52,
	EXTERMINATION_AGENT = 53,
	OPTIONAL_VOUCHER_PICK = 54,
	ACT_CART_COMPONENT = 55,
	VOUCHER_LEVELMAX_6 = 56,
	VOUCHER_LEVELMAX_5 = 57,
	VOUCHER_LEVELMAX_4 = 58,
	VOUCHER_SKILL_SPECIALLEVELMAX_6 = 59,
	VOUCHER_SKILL_SPECIALLEVELMAX_5 = 60,
	VOUCHER_SKILL_SPECIALLEVELMAX_4 = 61,
	ACTIVITY_POTENTIAL = 62,
	ITEM_PACK = 63,
	SANDBOX = 64,
	FAVOR_ADD_ITEM = 65,
	CLASSIC_SHD = 66,
	CLASSIC_TKT_GACHA = 67,
	CLASSIC_TKT_GACHA_10 = 68,
	LIMITED_BUFF = 69,
	CLASSIC_FES_PICK_TIER_5 = 70,
	CLASSIC_FES_PICK_TIER_6 = 71,
	RETURN_PROGRESS = 72,
	NEW_PROGRESS = 73,
	MCARD_VOUCHER = 74,
	MATERIAL_ISSUE_VOUCHER = 75,
	CRS_SHOP_COIN_V2 = 76,
	HOME_THEME = 77,
	SANDBOX_PERM = 78,
	SANDBOX_TOKEN = 79,
	TEMPLATE_TRAP = 80,
	NAME_CARD_SKIN = 81,
	EMOTICON_SET = 82,
	EXCLUSIVE_TKT_GACHA = 83,
	EXCLUSIVE_TKT_GACHA_10 = 84,
	SO_CHAR_EXP = 85,
	GIFTPACKAGE_TKT = 86,
	VOUCHER_SKIN_V2 = 87,
	RANDOM_VOUCHER_SKIN = 88,
	ACT1VHALFIDLE_ITEM = 89,
	PLOT_ITEM = 90,
	MAGAZINE_LEAF = 91,
	STICKER = 92
}

table Torappu_ItemBundle {
	id:string;
	count:int32;
	type:Torappu_ItemType;
}



table Torappu_MailArchiveItemData {
	id:string;
	type:Torappu_MailArchiveItemType;
	sortId:int32;
	displayReceiveTs:int64;
	year:int32;
	dateDelta:int32;
	senderId:string;
	title:string;
	content:string;
	rewardList:[Torappu_ItemBundle];
}



table Dict_2_System_String_Torappu_MailArchiveItemData_ {
	dict_key:string;
	dict_value:Torappu_MailArchiveItemData;
}



table Torappu_MailArchiveConstData {
	funcOpenTs:int64;
}



table Torappu_MailArchiveData {
	mailArchiveInfoDict:[Dict_2_System_String_Torappu_MailArchiveItemData_];
	constData:Torappu_MailArchiveConstData;
}



table Torappu_MailSenderSingleInfo {
	senderId:string;
	senderName:string;
	avatarId:string;
}



table Dict_2_System_String_Torappu_MailSenderSingleInfo_ {
	dict_key:string;
	dict_value:Torappu_MailSenderSingleInfo;
}



table Torappu_MailSenderData {
	senderDict:[Dict_2_System_String_Torappu_MailSenderSingleInfo_];
}



enum Torappu_EmojiSceneType : int32 {
	NONE = 0,
	ACTMULTIV3_ROOM = 1,
	ACTMULTIV3_PICK = 2,
	ACTMULTIV3_BATTLE = 3,
	ENEMYDUEL_BATTLE = 4,
	AUTOCHESS_ROOM = 5,
	AUTOCHESS_BATTLE = 6
}

table Torappu_EmoticonData_EmojiData {
	id:string;
	type:Torappu_EmojiSceneType;
	sortId:int32;
	picId:string;
	desc:string;
}



table Dict_2_System_String_Torappu_EmoticonData_EmojiData_ {
	dict_key:string;
	dict_value:Torappu_EmoticonData_EmojiData;
}



table Dict_2_System_String_List_1_System_String__ {
	dict_key:string;
	dict_value:[string];
}



table Torappu_EmoticonData {
	emojiDataDict:[Dict_2_System_String_Torappu_EmoticonData_EmojiData_];
	emoticonThemeDataDict:[Dict_2_System_String_List_1_System_String__];
}



table Torappu_StoryVariantData {
	plotTaskId:string;
	spStoryId:string;
	storyId:string;
	priority:int32;
	startTime:int64;
	endTime:int64;
	template:string;
	param:[string];
}



table Dict_2_System_String_Torappu_StoryVariantData_ {
	dict_key:string;
	dict_value:Torappu_StoryVariantData;
}



enum Torappu_UIGuideTarget : int32 {
	NONE = 0,
	BUILDING_CONTROL = 1,
	BUILDING_DORM = 2,
	BUILDING_HIRE = 3,
	BUILDING_MANUFACT = 4,
	BUILDING_MEETING = 5,
	BUILDING_TRADING = 6,
	CHAR_INFO = 7,
	FRIEND = 8,
	RECRUIT = 9,
	SHOP = 10,
	SQUAD_NORMAL = 11,
	SQUAD_BATTLE = 12,
	STAGE_MAINLINE = 13,
	BUILDING_POWER = 14,
	MISSION = 15,
	CHAR_SKILL_SELECT = 16,
	BUILDING_WORKSHOP = 17,
	STAGE_CAMPAIGN = 18,
	CHAR_EVOLVE = 19,
	HANDBOOK = 20,
	BUILDING_FURN_SHOP = 21,
	BUILDING_TRAINING = 22,
	STAGE_ACTIVITY = 23,
	CRISIS_STAGE = 24,
	ROGUELIKE_CHARSELECT = 25,
	ROGUELIKE_BP = 26,
	CLIMB_TOWER_ENTRY = 27,
	CLIMB_TOWER_LAYER = 28,
	ROGUELIKE_DUNGEON = 31,
	RL03_TOTEM = 32,
	GROCERY = 33,
	TUNING = 34,
	CRISIS_V2 = 35,
	MISSION_ARCHIVE = 36,
	FIFTH_ANNIV_EXPLORE = 37,
	CARVING = 38,
	VEC_BREAK = 39,
	FIREWORK = 40,
	BUILDING_STATION_MANAGE = 41,
	ACT_MULTI_V3 = 42,
	ENEMY_DUEL = 43,
	VEC_BREAK_V2 = 44,
	GUN_TASK = 45,
	SPECIAL_OPERATOR = 46,
	INFORMANT = 47,
	ACT1VHALFIDLE = 48,
	MONOPOLY = 49,
	AUTO_CHESS = 50,
	ART_GALLERY = 51,
	ART_MAGAZINE = 52
}

table Torappu_GuidebookConfigData {
	configId:string;
	sortId:int32;
	pageIdList:[string];
}



table Torappu_GuidebookGroupData {
	groupId:string;
	guideTarget:Torappu_UIGuideTarget;
	subSignal:string;
	configList:[Torappu_GuidebookConfigData];
}



table Dict_2_System_String_Torappu_GuidebookGroupData_ {
	dict_key:string;
	dict_value:Torappu_GuidebookGroupData;
}



enum Torappu_KeyCodeType : int32 {
	KEYBOARD = 0,
	MOUSE = 1
}

table Torappu_KeyItem {
	keyId:string;
	keyName:string;
	useIcon:bool;
	keyCodeType:Torappu_KeyCodeType;
	keyCodes:[int32];
	canBeSetted:bool;
}



table Dict_2_System_String_Torappu_KeyItem_ {
	dict_key:string;
	dict_value:Torappu_KeyItem;
}



enum Torappu_KeySettingGroup : int32 {
	BATTLE = 0,
	NORMAL = 1
}

enum Torappu_KeyEffectGroup : int32 {
	BATTLE = 0,
	OUT_BATTLE = 1,
	ALL = 2
}

enum Torappu_ActivityType : int32 {
	DEFAULT = 0,
	MISSION_ONLY = 1,
	CHECKIN_ONLY = 2,
	CHECKIN_ALL_PLAYER = 3,
	TYPE_ACT3D0 = 4,
	TYPE_ACT4D0 = 5,
	TYPE_ACT5D0 = 6,
	TYPE_ACT5D1 = 7,
	COLLECTION = 8,
	AVG_ONLY = 9,
	TYPE_ACT9D0 = 10,
	TYPE_ACT12SIDE = 11,
	TYPE_ACT13SIDE = 12,
	TYPE_ACT17SIDE = 13,
	LOGIN_ONLY = 14,
	MINISTORY = 15,
	ROGUELIKE = 16,
	PRAY_ONLY = 17,
	MULTIPLAY = 18,
	MULTIPLAY_VERIFY2 = 19,
	TYPE_ACT17D7 = 20,
	GRID_GACHA = 21,
	GRID_GACHA_V2 = 22,
	INTERLOCK = 23,
	APRIL_FOOL = 24,
	BOSS_RUSH = 25,
	TYPE_ACT20SIDE = 26,
	FLOAT_PARADE = 27,
	TYPE_ACT21SIDE = 28,
	MAIN_BUFF = 29,
	TYPE_ACT24SIDE = 30,
	FLIP_ONLY = 31,
	TYPE_ACT25SIDE = 32,
	CHECKIN_VS = 33,
	SWITCH_ONLY = 34,
	TYPE_ACT27SIDE = 35,
	UNIQUE_ONLY = 36,
	MAINLINE_BP = 37,
	TYPE_ACT42D0 = 38,
	TYPE_ACT29SIDE = 39,
	BLESS_ONLY = 40,
	CHECKIN_ACCESS = 41,
	YEAR_5_GENERAL = 42,
	TYPE_ACT35SIDE = 43,
	VEC_BREAK = 44,
	TYPE_ACT36SIDE = 45,
	TYPE_ACT38SIDE = 46,
	AUTOCHESS_VERIFY1 = 47,
	CHECKIN_VIDEO = 48,
	ARCADE = 49,
	MULTIPLAY_V3 = 50,
	TYPE_MAINSS = 51,
	ENEMY_DUEL = 52,
	VEC_BREAK_V2 = 53,
	TYPE_ACT42SIDE = 54,
	TYPE_ACT44SIDE = 55,
	HALFIDLE_VERIFY1 = 56,
	TYPE_ACT45SIDE = 57,
	TEAM_QUEST = 58,
	RECRUIT_ONLY = 59,
	TYPE_ACT46SIDE = 60,
	AUTOCHESS_SEASON = 61,
	ENUM = 62
}

table Torappu_KeySettingItemData {
	funcId:string;
	funcName:string;
	canBeSet:bool;
	defaultKeyId:string;
	sortId:int32;
}



table Torappu_KeySettingGroupData {
	groupId:string;
	name:string;
	funcType:Torappu_KeySettingGroup;
	keyEffectGroup:Torappu_KeyEffectGroup;
	isHidden:bool;
	relatedActType:Torappu_ActivityType;
	gameModeTag:string;
	sortId:int32;
	startTs:int64;
	itemList:[Torappu_KeySettingItemData];
}



table Torappu_ListDict_2_System_String_Torappu_KeySettingGroupData_ {
	dict_key:string;
	dict_value:Torappu_KeySettingGroupData;
}



table Torappu_PCKeyConstData {
	cannotSetKeyNotice:string;
	resetKeyNotice:string;
}



table Torappu_PCKeyData {
	keyList:[Dict_2_System_String_Torappu_KeyItem_];
	keySettingData:[Torappu_ListDict_2_System_String_Torappu_KeySettingGroupData_];
	constData:Torappu_PCKeyConstData;
}



table Torappu_ResolutionSettingItemData {
	sortId:int32;
	resolutionWidth:int32;
	resolutionHeight:int32;
	resolutionText:string;
	isFullScreen:bool;
	isBorderless:bool;
}



enum Torappu_CollectType : int32 {
	ALL = 0,
	ROGUE = 1,
	SANDBOX = 2
}

table Torappu_ArtGalleryCollectItemData {
	itemId:string;
	itemType:Torappu_ItemType;
	collectionSetId:string;
	sortId:int32;
}



table Torappu_ArtGalleryCollectSetMissionData {
	missionId:string;
	requireItemCount:int32;
	rewardList:[Torappu_ItemBundle];
}



table Torappu_ListDict_2_System_String_Torappu_ArtGalleryCollectSetMissionData_ {
	dict_key:string;
	dict_value:Torappu_ArtGalleryCollectSetMissionData;
}



table Torappu_ArtGalleryCollectSetData {
	setId:string;
	setName:string;
	setType:Torappu_CollectType;
	sortId:int32;
	startTime:int64;
	completeTime:int64;
	items:[Torappu_ArtGalleryCollectItemData];
	displayMaxCount:int32;
	missionList:[Torappu_ListDict_2_System_String_Torappu_ArtGalleryCollectSetMissionData_];
}



table Dict_2_System_String_Torappu_ArtGalleryCollectSetData_ {
	dict_key:string;
	dict_value:Torappu_ArtGalleryCollectSetData;
}



table Torappu_ArtGalleryCollectTypeData {
	setType:Torappu_CollectType;
	typeName:string;
	typeEngNameFilterPic:string;
	typeEngNamePic:string;
	typeFilterSelectIcon:string;
	typeFilterUnselectIcon:string;
	setIdList:[string];
	sortId:int32;
}



table Dict_2_System_String_Torappu_ArtGalleryCollectTypeData_ {
	dict_key:string;
	dict_value:Torappu_ArtGalleryCollectTypeData;
}



table Torappu_ArtGalleryCollectConstData {
	collectTypeFilterAll:string;
	collectTypeFilterAllUnselect:string;
}



table Torappu_ArtGalleryCollectData {
	collectionSets:[Dict_2_System_String_Torappu_ArtGalleryCollectSetData_];
	collectionTypes:[Dict_2_System_String_Torappu_ArtGalleryCollectTypeData_];
	constData:Torappu_ArtGalleryCollectConstData;
}



enum Torappu_MagazineLeafType : int32 {
	DEFAULT = 0,
	ROGUE = 1,
	SANDBOX = 2,
	AMIYA = 3
}

table UnityEngine_Vector2 {
}



table Dict_2_System_String_System_Int32_ {
	dict_key:string;
	dict_value:int32;
}



table Torappu_MagazineLeafItemData {
	leafId:string;
	leafType:Torappu_MagazineLeafType;
	sortId:int32;
	startTime:int64;
	name:string;
	desc:string;
	usage:string;
	approach:string;
	rarity:Torappu_ItemRarity;
	templateId:string;
	templateStartTime:int64;
	templateColor:string;
	skinDefaultPos:UnityEngine_Vector2;
	skinDefaultScale:float;
	leafDecorMaxNumMap:[Dict_2_System_String_System_Int32_];
}



table Dict_2_System_String_Torappu_MagazineLeafItemData_ {
	dict_key:string;
	dict_value:Torappu_MagazineLeafItemData;
}



table Torappu_MagazineLeafDecorTypeData {
	minScale:float;
	maxScale:float;
	defaultScale:float;
	engName:string;
	smallIconId:string;
	bigIconId:string;
	templateUseCardPosBias:UnityEngine_Vector2;
	templateUseCardScale:float;
}



table Dict_2_System_String_Torappu_MagazineLeafDecorTypeData_ {
	dict_key:string;
	dict_value:Torappu_MagazineLeafDecorTypeData;
}



table Torappu_MagazineLeafTypeData {
	engName:string;
	typeIconId:string;
}



table Dict_2_System_String_Torappu_MagazineLeafTypeData_ {
	dict_key:string;
	dict_value:Torappu_MagazineLeafTypeData;
}



table Torappu_ArtMagazineLeafElementData {
	id:string;
	type:Torappu_ItemType;
	sub:int32;
	pos:[float];
	scale:float;
}



table Torappu_ArtMagazineLeafData {
	leafId:string;
	decorList:[Torappu_ArtMagazineLeafElementData];
	charSkin:Torappu_ArtMagazineLeafElementData;
}



table Dict_2_System_String_Torappu_ArtMagazineLeafData_ {
	dict_key:string;
	dict_value:Torappu_ArtMagazineLeafData;
}



table Torappu_MagazineLeafConst {
	sysUnlockRewards:[Torappu_ItemBundle];
	leafDisplayMaxNum:int32;
	skinDefaultGainTime:int64;
	defaultLeafId:string;
}



table Dict_2_System_String_Dict_2_System_String_System_Int32__ {
	dict_key:string;
	dict_value:[Dict_2_System_String_System_Int32_];
}



table Torappu_MagazineLeafData {
	leafMap:[Dict_2_System_String_Torappu_MagazineLeafItemData_];
	leafDecorTypeMap:[Dict_2_System_String_Torappu_MagazineLeafDecorTypeData_];
	leafTypeMap:[Dict_2_System_String_Torappu_MagazineLeafTypeData_];
	leafTemplateMap:[Dict_2_System_String_Torappu_ArtMagazineLeafData_];
	constData:Torappu_MagazineLeafConst;
	blackListInDiy:[Dict_2_System_String_Dict_2_System_String_System_Int32__];
}



enum Torappu_StickerType : int32 {
	DEFAULT = 0,
	ROGUE = 1,
	SANDBOX = 2,
	AMIYA = 3
}

table Torappu_StickerItemData {
	id:string;
	name:string;
	stickerType:Torappu_StickerType;
	sortId:int32;
	desc:string;
	usage:string;
	approach:string;
	rarity:Torappu_ItemRarity;
}



table Dict_2_System_String_Torappu_StickerItemData_ {
	dict_key:string;
	dict_value:Torappu_StickerItemData;
}



table Torappu_StickerData {
	stickerMap:[Dict_2_System_String_Torappu_StickerItemData_];
}



table Torappu_AVGDialogPresetData {
	id:int32;
	name:string;
	nameFontSize:int32;
	messageFontSize:int32;
	messageMinHeight:float;
}



table Torappu_AVGDialogSettingData {
	defaultPresetId:int32;
	presetList:[Torappu_AVGDialogPresetData];
}



table Torappu_DisplayMetaData {
	playerAvatarData:Torappu_PlayerAvatarData;
	homeBackgroundData:Torappu_HomeBackgroundData;
	nameCardV2Data:Torappu_NameCardV2Data;
	mailArchiveData:Torappu_MailArchiveData;
	mailSenderData:Torappu_MailSenderData;
	emoticonData:Torappu_EmoticonData;
	storyVariantData:[Dict_2_System_String_Torappu_StoryVariantData_];
	guidebookGroupDatas:[Dict_2_System_String_Torappu_GuidebookGroupData_];
	pcKeyData:Torappu_PCKeyData;
	resolutionSettingList:[Torappu_ResolutionSettingItemData];
	artGalleryCollectData:Torappu_ArtGalleryCollectData;
	magazineLeafData:Torappu_MagazineLeafData;
	stickerData:Torappu_StickerData;
	avgDialogSettingData:Torappu_AVGDialogSettingData;
}



root_type Torappu_DisplayMetaData;