
table Torappu_OpenServerScheduleItem {
	id:string;
	versionId:string;
	startTs:int32;
	endTs:int32;
	totalCheckinDescption:string;
	chainLoginDescription:string;
	charImg:string;
}



enum Torappu_MissionType : int32 {
	UNKNOWN = 0,
	MAIN = 1,
	DAILY = 2,
	WEEKLY = 3,
	GUIDE = 4,
	SUB = 5,
	ACTIVITY = 6,
	OPENSERVER = 7,
	TOWERSEASON = 8,
	RETRO = 9,
	SPECIAL_OPERATOR = 10,
	SPECIAL_OPERATOR_WEEKLY = 11
}

enum Torappu_ItemType : int32 {
	NONE = 0,
	CHAR = 1,
	CARD_EXP = 2,
	MATERIAL = 3,
	GOLD = 4,
	EXP_PLAYER = 5,
	TKT_TRY = 6,
	TKT_RECRUIT = 7,
	TKT_INST_FIN = 8,
	TKT_GACHA = 9,
	ACTIVITY_COIN = 10,
	DIAMOND = 11,
	DIAMOND_SHD = 12,
	HGG_SHD = 13,
	LGG_SHD = 14,
	FURN = 15,
	AP_GAMEPLAY = 16,
	AP_BASE = 17,
	SOCIAL_PT = 18,
	CHAR_SKIN = 19,
	TKT_GACHA_10 = 20,
	TKT_GACHA_PRSV = 21,
	AP_ITEM = 22,
	AP_SUPPLY = 23,
	RENAMING_CARD = 24,
	RENAMING_CARD_2 = 25,
	ET_STAGE = 26,
	ACTIVITY_ITEM = 27,
	VOUCHER_PICK = 28,
	VOUCHER_CGACHA = 29,
	VOUCHER_MGACHA = 30,
	CRS_SHOP_COIN = 31,
	CRS_RUNE_COIN = 32,
	LMTGS_COIN = 33,
	EPGS_COIN = 34,
	LIMITED_TKT_GACHA_10 = 35,
	LIMITED_FREE_GACHA = 36,
	REP_COIN = 37,
	ROGUELIKE = 38,
	LINKAGE_TKT_GACHA_10 = 39,
	VOUCHER_ELITE_II_4 = 40,
	VOUCHER_ELITE_II_5 = 41,
	VOUCHER_ELITE_II_6 = 42,
	VOUCHER_SKIN = 43,
	RETRO_COIN = 44,
	PLAYER_AVATAR = 45,
	UNI_COLLECTION = 46,
	VOUCHER_FULL_POTENTIAL = 47,
	RL_COIN = 48,
	RETURN_CREDIT = 49,
	MEDAL = 50,
	CHARM = 51,
	HOME_BACKGROUND = 52,
	EXTERMINATION_AGENT = 53,
	OPTIONAL_VOUCHER_PICK = 54,
	ACT_CART_COMPONENT = 55,
	VOUCHER_LEVELMAX_6 = 56,
	VOUCHER_LEVELMAX_5 = 57,
	VOUCHER_LEVELMAX_4 = 58,
	VOUCHER_SKILL_SPECIALLEVELMAX_6 = 59,
	VOUCHER_SKILL_SPECIALLEVELMAX_5 = 60,
	VOUCHER_SKILL_SPECIALLEVELMAX_4 = 61,
	ACTIVITY_POTENTIAL = 62,
	ITEM_PACK = 63,
	SANDBOX = 64,
	FAVOR_ADD_ITEM = 65,
	CLASSIC_SHD = 66,
	CLASSIC_TKT_GACHA = 67,
	CLASSIC_TKT_GACHA_10 = 68,
	LIMITED_BUFF = 69,
	CLASSIC_FES_PICK_TIER_5 = 70,
	CLASSIC_FES_PICK_TIER_6 = 71,
	RETURN_PROGRESS = 72,
	NEW_PROGRESS = 73,
	MCARD_VOUCHER = 74,
	MATERIAL_ISSUE_VOUCHER = 75,
	CRS_SHOP_COIN_V2 = 76,
	HOME_THEME = 77,
	SANDBOX_PERM = 78,
	SANDBOX_TOKEN = 79,
	TEMPLATE_TRAP = 80,
	NAME_CARD_SKIN = 81,
	EMOTICON_SET = 82,
	EXCLUSIVE_TKT_GACHA = 83,
	EXCLUSIVE_TKT_GACHA_10 = 84,
	SO_CHAR_EXP = 85,
	GIFTPACKAGE_TKT = 86,
	VOUCHER_SKIN_V2 = 87,
	RANDOM_VOUCHER_SKIN = 88,
	ACT1VHALFIDLE_ITEM = 89,
	PLOT_ITEM = 90,
	MAGAZINE_LEAF = 91,
	STICKER = 92
}

table Torappu_MissionDisplayRewards {
	type:Torappu_ItemType;
	id:string;
	count:int32;
}



table Torappu_MissionGroup {
	id:string;
	title:string;
	type:Torappu_MissionType;
	preMissionGroup:string;
	period:[int32];
	rewards:[Torappu_MissionDisplayRewards];
	missionIds:[string];
	startTs:int64;
	endTs:int64;
}



enum Torappu_MissionItemBgType : int32 {
	COMMON = 0,
	Equipment = 1,
	Char = 2
}

table Torappu_MissionData {
	id:string;
	sortId:int32;
	description:string;
	type:Torappu_MissionType;
	itemBgType:Torappu_MissionItemBgType;
	preMissionIds:[string];
	template:string;
	templateType:string;
	param:[string];
	unlockCondition:string;
	unlockParam:[string];
	missionGroup:string;
	toPage:string;
	periodicalPoint:int32;
	rewards:[Torappu_MissionDisplayRewards];
	backImagePath:string;
	foldId:string;
	haveSubMissionToUnlock:bool;
	countEndTs:int64;
}



table Torappu_OpenServerItemData {
	itemId:string;
	itemType:Torappu_ItemType;
	count:int32;
	name:string;
}



table Torappu_TotalCheckinData {
	order:int32;
	item:Torappu_OpenServerItemData;
	colorId:int32;
}



table Torappu_ChainLoginData {
	order:int32;
	item:Torappu_OpenServerItemData;
	colorId:int32;
}



table Torappu_OpenServerData {
	openServerMissionGroup:Torappu_MissionGroup;
	openServerMissionData:[Torappu_MissionData];
	checkInData:[Torappu_TotalCheckinData];
	chainLoginData:[Torappu_ChainLoginData];
	totalCheckinCharData:[string];
	chainLoginCharData:[string];
}



table Dict_2_System_String_Torappu_OpenServerData_ {
	dict_key:string;
	dict_value:Torappu_OpenServerData;
}



table Torappu_OpenServerConst {
	firstDiamondShardMailCount:int32;
	initApMailEndTs:int64;
	resFullOpenUnlockStageId:string;
	resFullOpenDuration:int32;
	resFullOpenTitle:string;
	resFullOpenDesc:string;
	resFullOpenGuideGroupThreshold:string;
	resFullOpenStartTime:int64;
}



enum Torappu_ReturnAllOpenType : int32 {
	RESOURCE = 0,
	CAMP = 1
}

table Torappu_ReturnOpenData {
	allOpenType:Torappu_ReturnAllOpenType;
	allOpenTime:int32;
	desc:string;
}



table Torappu_ReturnGroupData {
	groupId:string;
	taskDays:int32;
	onceGroupId:string;
	missionGroupId:[string];
	checkinGroupId:string;
	priceGroupId:string;
	newsGroupId:[string];
	giftPackageIdList:[string];
	checkinGpId:string;
	gachaPoolId:string;
	allOpenDays:int32;
	campAllOpenDays:int32;
	allOpenData:[Torappu_ReturnOpenData];
}



table Dict_2_System_String_Torappu_ReturnGroupData_ {
	dict_key:string;
	dict_value:Torappu_ReturnGroupData;
}



table Torappu_ReturnItemData {
	id:string;
	count:int32;
	type:Torappu_ItemType;
	sortId:int32;
}



table Torappu_ReturnOnceRewardData {
	groupId:string;
	rewardList:[Torappu_ReturnItemData];
}



table Dict_2_System_String_Torappu_ReturnOnceRewardData_ {
	dict_key:string;
	dict_value:Torappu_ReturnOnceRewardData;
}



table Torappu_ItemBundle {
	id:string;
	count:int32;
	type:Torappu_ItemType;
}



table Torappu_ReturnCheckinItemData {
	order:int32;
	isKeyItem:bool;
	rewardList:[Torappu_ItemBundle];
}



table Torappu_ReturnCheckinGroupData {
	groupId:string;
	checkinItemList:[Torappu_ReturnCheckinItemData];
}



table Dict_2_System_String_Torappu_ReturnCheckinGroupData_ {
	dict_key:string;
	dict_value:Torappu_ReturnCheckinGroupData;
}



table Torappu_ReturnPriceItemData {
	contentId:string;
	sortId:int32;
	pointRequire:int32;
	desc:string;
	displayReward:Torappu_ReturnItemData;
	rewardList:[Torappu_ReturnItemData];
}



table Torappu_ReturnPriceGroupData {
	groupId:string;
	content:[Torappu_ReturnPriceItemData];
}



table Dict_2_System_String_Torappu_ReturnPriceGroupData_ {
	dict_key:string;
	dict_value:Torappu_ReturnPriceGroupData;
}



enum Torappu_ReturnMissionGroupType : int32 {
	DAILY = 0,
	NORMAL = 1,
	DIFF = 2
}

enum Torappu_ReturnJumpType : int32 {
	NONE = 0,
	ZONE_GROUP = 1,
	ROGUE = 2,
	CLIMB_TOWER = 3,
	CAMPAIGN = 4,
	BUILDING = 5,
	RECRUIT_BUILD = 6,
	DAILY_MISSION = 7,
	SANDBOX = 8,
	MAIN_SS = 9
}

table Torappu_ReturnMissionItemData {
	missionId:string;
	sortId:int32;
	uncompleteBgIcon:string;
	completeBgIcon:string;
	desc:string;
	jumpType:Torappu_ReturnJumpType;
	jumpPlace:string;
	rewardList:[Torappu_ItemBundle];
}



table Torappu_ReturnMissionGroupData {
	groupId:string;
	sortId:int32;
	type:Torappu_ReturnMissionGroupType;
	missionList:[Torappu_ReturnMissionItemData];
}



table Dict_2_System_String_Torappu_ReturnMissionGroupData_ {
	dict_key:string;
	dict_value:Torappu_ReturnMissionGroupData;
}



table Dict_2_System_Int32_List_1_Torappu_ReturnItemData__ {
	dict_key:int32;
	dict_value:[Torappu_ReturnItemData];
}



table Torappu_ReturnCheckinGpRewardData {
	groupId:string;
	getTime:int32;
	bindGPGoodId:string;
	totalCheckInDay:int32;
	iconId:string;
	rewardDict:[Dict_2_System_Int32_List_1_Torappu_ReturnItemData__];
}



table Dict_2_System_String_Torappu_ReturnCheckinGpRewardData_ {
	dict_key:string;
	dict_value:Torappu_ReturnCheckinGpRewardData;
}



enum Torappu_ReturnNewsType : int32 {
	NONE = 0,
	MAIN_SS = 1,
	ROGUE = 2,
	SANDBOX = 3
}

table Torappu_ReturnNewsData {
	groupId:string;
	sortId:int32;
	tabTitle:string;
	tabIcon:string;
	title:string;
	desc:string;
	imgId:string;
	iconId:string;
	jumpType:Torappu_ReturnNewsType;
	jumpPlace:string;
}



table Dict_2_System_String_Torappu_ReturnNewsData_ {
	dict_key:string;
	dict_value:Torappu_ReturnNewsData;
}



table Torappu_ReturnGiftPackagePicData {
	giftPackageId:string;
	giftPackagePic:string;
	sortId:int32;
}



table Dict_2_System_String_Torappu_ReturnGiftPackagePicData_ {
	dict_key:string;
	dict_value:Torappu_ReturnGiftPackagePicData;
}



table Torappu_ReturnOpenStyleData {
	sortId:int32;
	imgBkgId:string;
	imgEntryId:string;
	imgIconId:string;
	pauseDesc:string;
	title:string;
	name:string;
}



table Dict_2_System_String_Torappu_ReturnOpenStyleData_ {
	dict_key:string;
	dict_value:Torappu_ReturnOpenStyleData;
}



table Torappu_ReturnConstData {
	pointItemId:string;
	returnPriceDesc:string;
	oldReturnGroupId:string;
}



table Torappu_ReturnData {
	groupDataMap:[Dict_2_System_String_Torappu_ReturnGroupData_];
	onceDataMap:[Dict_2_System_String_Torappu_ReturnOnceRewardData_];
	checkinDataMap:[Dict_2_System_String_Torappu_ReturnCheckinGroupData_];
	priceDataMap:[Dict_2_System_String_Torappu_ReturnPriceGroupData_];
	missionDataMap:[Dict_2_System_String_Torappu_ReturnMissionGroupData_];
	checkinGpData:[Dict_2_System_String_Torappu_ReturnCheckinGpRewardData_];
	newsDataMap:[Dict_2_System_String_Torappu_ReturnNewsData_];
	giftPackagePicDataMap:[Dict_2_System_String_Torappu_ReturnGiftPackagePicData_];
	openStyleData:[Dict_2_System_String_Torappu_ReturnOpenStyleData_];
	constData:Torappu_ReturnConstData;
}



table Torappu_NewbieCheckInPackageRewardData {
	orderNum:int32;
	itemBundle:Torappu_ItemBundle;
}



table Dict_2_System_Int32_List_1_Torappu_NewbieCheckInPackageRewardData__ {
	dict_key:int32;
	dict_value:[Torappu_NewbieCheckInPackageRewardData];
}



table Torappu_NewbieCheckInPackageData {
	groupId:string;
	startTime:int64;
	endTime:int64;
	bindGPGoodId:string;
	checkInDuration:int32;
	compensateEndDay:int32;
	totalCheckInDay:int32;
	iconId:string;
	checkInRewardDict:[Dict_2_System_Int32_List_1_Torappu_NewbieCheckInPackageRewardData__];
	trigStartTime:int64;
	trigEndTime:int64;
}



table Torappu_LongTermCheckInGroupData {
	groupId:string;
	sortId:int32;
	startTs:int64;
	level:int32;
	days:int32;
	bkgImgId:string;
	titleImgId:string;
	tipText:string;
	bottomText:string;
	rewardList:[Torappu_ItemBundle];
}



table Torappu_LongTermCheckInConstData {
	startTs:int64;
	detailTitle:string;
	detailDesc:string;
}



table Torappu_LongTermCheckInData {
	groupList:[Torappu_LongTermCheckInGroupData];
	constData:Torappu_LongTermCheckInConstData;
}



table Torappu_OpenServerSchedule {
	schedule:[Torappu_OpenServerScheduleItem];
	dataMap:[Dict_2_System_String_Torappu_OpenServerData_];
	constant:Torappu_OpenServerConst;
	playerReturn:Torappu_ReturnData;
	newbieCheckInPackageList:[Torappu_NewbieCheckInPackageData];
	longTermCheckInData:Torappu_LongTermCheckInData;
}



root_type Torappu_OpenServerSchedule;