include "Torappu_PlayerAvatarGroupType.fbs";
include "Torappu_PlayerAvatarLimitData.fbs";

table Torappu_PlayerAvatarPerData {
	avatarId:string;
	avatarType:Torappu_PlayerAvatarGroupType;
	avatarDesc:string;
	isSecret:bool;
	avatarStartTs:int64;
	avatarLimit:bool;
	avatarIdSort:int32;
	avatarIdDesc:string;
	avatarItemName:string;
	avatarItemDesc:string;
	avatarItemUsage:string;
	obtainApproach:string;
	dynAvatarId:string;
	limitDatas:[Torappu_PlayerAvatarLimitData];
}


root_type Torappu_PlayerAvatarPerData;