include "Dict_2_System_String_Torappu_ReturnGroupData_.fbs";
include "Dict_2_System_String_Torappu_ReturnOnceRewardData_.fbs";
include "Dict_2_System_String_Torappu_ReturnCheckinGroupData_.fbs";
include "Dict_2_System_String_Torappu_ReturnPriceGroupData_.fbs";
include "Dict_2_System_String_Torappu_ReturnMissionGroupData_.fbs";
include "Dict_2_System_String_Torappu_ReturnCheckinGpRewardData_.fbs";
include "Dict_2_System_String_Torappu_ReturnNewsData_.fbs";
include "Dict_2_System_String_Torappu_ReturnGiftPackagePicData_.fbs";
include "Dict_2_System_String_Torappu_ReturnOpenStyleData_.fbs";
include "Torappu_ReturnConstData.fbs";

table Torappu_ReturnData {
	groupDataMap:[Dict_2_System_String_Torappu_ReturnGroupData_];
	onceDataMap:[Dict_2_System_String_Torappu_ReturnOnceRewardData_];
	checkinDataMap:[Dict_2_System_String_Torappu_ReturnCheckinGroupData_];
	priceDataMap:[Dict_2_System_String_Torappu_ReturnPriceGroupData_];
	missionDataMap:[Dict_2_System_String_Torappu_ReturnMissionGroupData_];
	checkinGpData:[Dict_2_System_String_Torappu_ReturnCheckinGpRewardData_];
	newsDataMap:[Dict_2_System_String_Torappu_ReturnNewsData_];
	giftPackagePicDataMap:[Dict_2_System_String_Torappu_ReturnGiftPackagePicData_];
	openStyleData:[Dict_2_System_String_Torappu_ReturnOpenStyleData_];
	constData:Torappu_ReturnConstData;
}


root_type Torappu_ReturnData;