include "Torappu_PlayerAvatarData.fbs";
include "Torappu_HomeBackgroundData.fbs";
include "Torappu_NameCardV2Data.fbs";
include "Torappu_MailArchiveData.fbs";
include "Torappu_MailSenderData.fbs";
include "Torappu_EmoticonData.fbs";
include "Dict_2_System_String_Torappu_StoryVariantData_.fbs";
include "Dict_2_System_String_Torappu_GuidebookGroupData_.fbs";
include "Torappu_PCKeyData.fbs";
include "Torappu_ResolutionSettingItemData.fbs";
include "Torappu_ArtGalleryCollectData.fbs";
include "Torappu_MagazineLeafData.fbs";
include "Torappu_StickerData.fbs";
include "Torappu_AVGDialogSettingData.fbs";

table Torappu_DisplayMetaData {
	playerAvatarData:Torappu_PlayerAvatarData;
	homeBackgroundData:Torappu_HomeBackgroundData;
	nameCardV2Data:Torappu_NameCardV2Data;
	mailArchiveData:Torappu_MailArchiveData;
	mailSenderData:Torappu_MailSenderData;
	emoticonData:Torappu_EmoticonData;
	storyVariantData:[Dict_2_System_String_Torappu_StoryVariantData_];
	guidebookGroupDatas:[Dict_2_System_String_Torappu_GuidebookGroupData_];
	pcKeyData:Torappu_PCKeyData;
	resolutionSettingList:[Torappu_ResolutionSettingItemData];
	artGalleryCollectData:Torappu_ArtGalleryCollectData;
	magazineLeafData:Torappu_MagazineLeafData;
	stickerData:Torappu_StickerData;
	avgDialogSettingData:Torappu_AVGDialogSettingData;
}


root_type Torappu_DisplayMetaData;