include "Torappu_ActAutoChessBondActiveConditionType.fbs";
include "Torappu_ActAutoChessBondActiveType.fbs";

table Torappu_ActAutoChessData_ActAutoChessBondInfo {
	bondId:string;
	name:string;
	desc:string;
	iconId:string;
	activeCount:int32;
	activeCondition:Torappu_ActAutoChessBondActiveConditionType;
	activeConditionTemplate:string;
	activeParamList:[string];
	effectId:string;
	activeType:Torappu_ActAutoChessBondActiveType;
	identifier:int32;
	weight:int32;
	isActiveInDeck:bool;
	maxInactiveBondCount:int32;
	descParamBaseList:[string];
	descParamPerStackList:[string];
	noStack:bool;
	chessIdList:[string];
}


root_type Torappu_ActAutoChessData_ActAutoChessBondInfo;